---
openapi: 3.1.0
info:
  description: Example API spec
  version: v1
  title: Example
  contact:
    name: Example
    email: example@example.com
    url: www.example.com
  license:
    name: Example
    url: www.example.com
tags:
  - name: Account
    description: Account
servers:
  - url: https://<hidden>
paths:
  /api/v1/Accounts:
    get:
      summary: TODO
      description: TODO
      security:
        - BearerAuth: []
      tags:
        - Account
      operationId: listAccounts
      responses:
        "200":
          $ref: ./schemas/components.openapi.yaml#/components/responses/ListAccounts
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
